export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_USER_FROM_LOCAL_STORAGE = 'GET_USER_FROM_LOCAL_STORAGE';